[zta_nodes]
labubuntu2 ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[windows_nodes]
desktop-fbrjp25 ansible_host=100.113.109.76 ansible_user=Administrator ansible_connection=winrm
